from typing import Protocol, Any, Dict, List, Optional, Tuple, Union


# -------------------------------
# SQL ADAPTER CONTRACT
# -------------------------------
class SQLAdapter(Protocol):
    def insert(self, table: str, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def select(
        self,
        table: str,
        query: Dict[str, Any],
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> List[Dict[str, Any]]: ...
    def select_page(
        self, table: str, query: Dict[str, Any], page_size: int, continuation_token: Optional[str]
    ) -> Tuple[List[Dict[str, Any]], Optional[str]]: ...
    def update(self, table: str, entity_id: Any, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete(self, table: str, entity_id: Any) -> Dict[str, Any]: ...
    def upsert(self, table: str, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def query_linq(self, table: str, builder: Any) -> Union[List[Dict[str, Any]], int]: ...
    def execute(self, sql: str, params: Optional[List[Any]] = None) -> Any: ...


# -------------------------------
# NOSQL ADAPTER CONTRACT
# -------------------------------
class NoSQLAdapter(Protocol):
    def put(self, model: type, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def query(
        self, model: type, query: Dict[str, Any], limit: Optional[int] = None
    ) -> List[Dict[str, Any]]: ...
    def query_page(
        self, model: type, query: Dict[str, Any], page_size: int, continuation_token: Optional[str]
    ) -> Tuple[List[Dict[str, Any]], Optional[str]]: ...
    def patch(self, model: type, entity_id: Any, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete(self, model: type, entity_id: Any) -> Dict[str, Any]: ...
    def upsert(self, model: type, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def query_linq(self, model: type, builder: Any) -> Union[List[Dict[str, Any]], int]: ...


# -------------------------------
# OBJECT STORAGE
# -------------------------------
class ObjectStorage(Protocol):
    def put(self, key: str, data: bytes, **kwargs) -> str: ...
    def get(self, key: str) -> Optional[bytes]: ...
    def delete(self, key: str) -> bool: ...
    def list(self, prefix: str = "") -> List[str]: ...


# -------------------------------
# QUEUE (FIXED)
# -------------------------------
class QueueService(Protocol):
    def publish(
        self, queue_name: str, message: Dict[str, Any], delay: Optional[int] = None
    ) -> None: ...
    def consume(
        self, queue_name: str, max_messages: int, wait_seconds: int
    ) -> List[Dict[str, Any]]: ...
    def ack(self, queue_name: str, receipt_handle: str) -> None: ...
    def nack(self, queue_name: str, receipt_handle: str, delay: Optional[int] = None) -> None: ...


# -------------------------------
# CACHE
# -------------------------------
class CacheService(Protocol):
    def set(self, key: str, value: Any, ttl: int) -> None: ...
    def get(self, key: str) -> Optional[Any]: ...
    def delete(self, key: str) -> None: ...


# -------------------------------
# FINAL RUNTIME CONTRACT
# -------------------------------
class DataAccessRuntime(Protocol):

    # high-level CRUD (used by UDL)
    def create(self, model: Any, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def read(
        self,
        model: Any,
        query: Dict[str, Any],
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> List[Dict[str, Any]]: ...
    def read_one(self, model: Any, query: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def update(self, model: Any, entity_id: Any, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete(self, model: Any, entity_id: Any) -> Any: ...
    def upsert(self, model: Any, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def query_linq(self, model: Any, builder: Any) -> Union[List[Dict[str, Any]], int]: ...

    # adapters (CRITICAL)
    def get_sql(self) -> SQLAdapter: ...
    def get_nosql_kv(self) -> NoSQLAdapter: ...
    def get_object_storage(self) -> ObjectStorage: ...
    def get_queue(self) -> QueueService: ...
    def get_cache(self) -> CacheService: ...
